/* Automatically generated by po2tbl.sed from dcfldd.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"invalid argument %s for `%s'", 2},
  {"ambiguous argument %s for `%s'", 3},
  {"Valid arguments are:", 4},
  {"write error", 5},
  {"Unknown system error", 6},
  {"%s: option `%s' is ambiguous\n", 7},
  {"%s: option `--%s' doesn't allow an argument\n", 8},
  {"%s: option `%c%s' doesn't allow an argument\n", 9},
  {"%s: option `%s' requires an argument\n", 10},
  {"%s: unrecognized option `--%s'\n", 11},
  {"%s: unrecognized option `%c%s'\n", 12},
  {"%s: illegal option -- %c\n", 13},
  {"%s: invalid option -- %c\n", 14},
  {"%s: option requires an argument -- %c\n", 15},
  {"%s: option `-W %s' is ambiguous\n", 16},
  {"%s: option `-W %s' doesn't allow an argument\n", 17},
  {"block size", 18},
  {"cannot create directory %s", 19},
  {"%s exists but is not a directory", 20},
  {"cannot change owner and/or group of %s", 21},
  {"cannot chdir to directory, %s", 22},
  {"cannot change permissions of %s", 23},
  {"memory exhausted", 24},
  {"`", 25},
  {"'", 26},
  {"^[yY]", 27},
  {"^[nN]", 28},
  {"cannot output U+%04X: iconv function not usable", 29},
  {"U+%04X: character out of range", 30},
  {"cannot convert U+%04X to local character set", 31},
  {"cannot output U+%04X: iconv function not available", 32},
  {"invalid user", 33},
  {"invalid group", 34},
  {"cannot get the login group of a numeric UID", 35},
  {"cannot omit both user and group", 36},
  {"Copyright (C) 2001 Free Software Foundation, Inc.", 37},
  {"Written by %s.\n", 38},
  {"\
This is free software; see the source for copying conditions.  There is NO\n\
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n", 39},
  {"Try `%s --help' for more information.\n", 40},
  {"Usage: %s [OPTION]...\n", 41},
  {"\
Copy a file, converting and formatting according to the options.\n\
\n\
  bs=BYTES             force ibs=BYTES and obs=BYTES\n\
  cbs=BYTES            convert BYTES bytes at a time\n\
  conv=KEYWORDS        convert the file as per the comma separated keyword \
list\n\
  count=BLOCKS         copy only BLOCKS input blocks\n\
  ibs=BYTES            read BYTES bytes at a time\n\
  if=FILE              read from FILE instead of stdin\n\
  obs=BYTES            write BYTES bytes at a time\n\
  of=FILE              write to FILE instead of stdout\n\
  seek=BLOCKS          skip BLOCKS obs-sized blocks at start of output\n\
  skip=BLOCKS          skip BLOCKS ibs-sized blocks at start of input\n\
  pattern=BYTES        use the specified binary pattern as input\n\
  textpattern=TEXT     use repeating TEXT as input\n\
  hashwindow=BYTES     perform an MD5 hash on every BYTES amount of data\n\
  hashlog=FILE         send MD5 hash output to FILE instead of stderr\n\
  status=[on|off]      display a continual status message on stderr\n\
                         default state is \"on\"\n\
  sizeprobe=[if|of]    determine the size of the input or output file", 42},
  {"\
\n\
Report bugs to <bug-fileutils@gnu.org>.", 43},
  {"%s+%s records in\n", 44},
  {"%s+%s records out\n", 45},
  {"truncated record", 46},
  {"truncated records", 47},
  {"closing input file %s", 48},
  {"closing output file %s", 49},
  {"writing to %s", 50},
  {"invalid conversion: %s", 51},
  {"unrecognized option %s", 52},
  {"invalid hex pattern: %s", 53},
  {"opening %s", 54},
  {"unrecognized option %s=%s", 55},
  {"invalid number %s", 56},
  {"\
only one conv in {ascii,ebcdic,ibm}, {lcase,ucase}, {block,unblock}, \
{unblock,sync}", 57},
  {"reading %s", 58},
  {"writing %s", 59},
  {"stating file", 60},
  {"standard input", 61},
  {"file offset out of range", 62},
  {"cannot fstat %s", 63},
  {"advancing past %s bytes in output file %s", 64},
  {"standard output", 65},
};
int _msg_tbl_length = 65;
